# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['client/game/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('client', 'client'),
    ],
    hiddenimports=[
        'blessed',
        'keyboard',
        'socketio',
        'engineio',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'websocket',
        'bidict',
        'python_engineio',
        'simple_websocket',
        'game.ui.interactiveuis.farmui',
        'game.ui.interactiveuis.alchemist_ui',
        'game.ui.interactiveuis.bank_ui',
        'game.ui.interactiveuis.landlord_ui',
        'game.ui.interactiveuis.yago_ui',
        'game.ui.interactiveuis.rank_ui',
        'game.items.materials',
        'game.items.potions',
        'game.items.swords',
        'game.arts.buildings',
        'game.arts.farm_elements',
        'game.arts.merchant',
        'game.arts.bank',
        'game.arts.rank',
        'game.arts.materials',
        'game.mechanics.farm.farm',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CmdMMO',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
